Poc_task/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Poc_task.Models;
using System.IO;

namespace Poc_task.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Employee emp)
        { 
        //{  if(ModelState.IsValid)
        //    {
                
        //        return Content(emp.FirstName);
        //    }
        //    return View("Index");
            try
            {
                if (ModelState.IsValid)
                {
                   EmployeeDBContext EmpRepo = new EmployeeDBContext();

                    if (EmpRepo.AddEmployee(emp))
                    {
                        ViewBag.Message = "Employee details added successfully";
                    }
                }

                return View();
            }
            catch
            {
                return View();
            }

        }
        public ActionResult Bootstrap()
        {
            return View();
        }
        public ActionResult ViewRecords()
        {
            EmployeeDBContext db = new EmployeeDBContext();
            List<Employee> obj = db.GetAllEmployees();

            return View(obj);

        }
        public ActionResult CreateRecord()
        { 

            return View();
        }
        [HttpPost]
        public ActionResult CreateRecord(Employee emp,HttpPostedFileBase UploadFile)
        {
            try
            {   if ( UploadFile.ContentLength>0)
                {
                    string FileName = Path.GetFileName(UploadFile.FileName);

                    string path = Server.MapPath("~/App_Start/File Uploads");
                    
                    string fullPath = Path.Combine(path, FileName);
                    UploadFile.SaveAs(fullPath);
                }
            }
            catch
            {
                ViewBag.Message = "File upload failed";
                return View();
            }

            try
            {
                if (ModelState.IsValid)
                {
                    EmployeeDBContext EmpRepo = new EmployeeDBContext();

                    if (EmpRepo.AddEmployee(emp))
                    {
                        ViewBag.Message = "Employee details added successfully";
                    }
                }

                return View(ViewBag.Message);
            }
            catch
            {
                return View();
            }
            
        }
        [HttpGet]
        public ActionResult DeleteRecord(string empcode)
        {
              //EmployeeDBContext EmpRepo = new EmployeeDBContext();
            // var row = EmpRepo.GetEmployees().Find(model => model.EmpCode == empcode);
            try
            {
                EmployeeDBContext EmpRepo = new EmployeeDBContext();
                if(EmpRepo.DeleteEmployee(empcode))
                {
                    ViewBag.AlertMsg = "Employees Details Deleted Successfully";
                }
                return RedirectToAction("ViewRecords");
            }
            catch
            {
                return View();
            }
           return RedirectToAction("");
            
        }
        [HttpPost]
        //public ActionResult DeleteRecord(String empcode,Employee emp)
        //{
        //    EmployeeDBContext EmpRepo = new EmployeeDBContext();
        //    bool check = EmpRepo.DeleteEmployee(empcode);
        //    if(check==true)
        //    {
        //        TempData["DeleteMessage"] = "Data Has Been Deleted Successfully";
        //        ModelState.Clear();
        //        return RedirectToAction("CreateRecord");

        //    }
        //    return View();



        //}
        public ActionResult Delete()
        {
            return View();
        }
        // from start
        public ActionResult InsertRecord()
        {
            return View();
        }
        //public ActionResult FileUpload()
        //{
        //    ret
        //}

    }
}

Poc_task/Views/Default/CreateRecord.cshtml
@model Poc_task.Models.Employee

@{
    ViewBag.Title = "CreateRecord";
}

<h2>CreateRecord</h2>

@using (Html.BeginForm("CreateRecord","default",FormMethod.Post ,new { @enctype = "multipart/form-data" } ))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Employee</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.EmpCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmpCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmpCode, "", new { @class = "text-danger" })
        </div>
    </div>

    

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sex, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">

            @Html.TextBox("UploadFile", "", new { type = "file" }) <br />
            <input type="submit" value="UploadFile" />
            @ViewBag.Message


            @*<input type="file" name="file" value="upload" class="btn btn-default" />*@
        </div>


    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Poc_task/Views/Default/Delete.cshtml
@model Poc_task.Models.Employee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
       

        <dt>
            @Html.DisplayNameFor(model => model.EmpCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpCode)
        </dd>

       

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Poc_task/Views/Default/DeleteRecord.cshtml
@model Poc_task.Models.Employee

@{
    ViewBag.Title = "DeleteRecord";
}

<h2>DeleteRecord</h2>

@using (Html.BeginForm("DeleteRecord","Default",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    

        <div class="form-group">
            @Html.LabelFor(model => model.EmpCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpCode, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-default" />
            </div>
        </div>
    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Poc_task/Views/Default/DisplayRecords.cshtml
@{
    ViewBag.Title = "DisplayRecords";
}

<h2>DisplayRecords</h2>

Poc_task/Views/Default/FileUpload.cshtml
@{
    ViewBag.Title = "FileUpload";
}

<h2>FileUpload</h2>

Poc_task/Views/Default/Index.cshtml
@model Poc_task.Models.Employee
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        body {
            background-color: lightgrey;
            color: black;
        }

        label {
            color: blue;
            font-size: large;
        }

        a {
            font-size: large;
        }

        .head_container {
            display: flex;
            justify-content: center;
            font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        }

        .head_container_link {
            display: flex;
            justify-content: space-between;
            font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        }

        .head_container_form {
            display: flex;
            flex-flow: row nowrap;
            justify-content: center;
            font-size: large;
        }

        .form_button {
            display: flex;
            justify-content: space-around;
            font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        }
    </style>
</head>
<body>
   
    <div class="head_container_form">
        @using (Html.BeginForm("PostUsingBinding", "Default", FormMethod.Post))
        {
            @Html.LabelFor(model => model.EmpCode)
            @Html.EditorFor(model => model.EmpCode)
            @Html.ValidationMessageFor(model => model.EmpCode)
            <br />
            <br />

            @Html.LabelFor(model => model.FirstName)
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)

            <br />
            @Html.LabelFor(model => model.LastName)
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)

            <br />
            @Html.LabelFor(model => model.Age)
            @Html.EditorFor(model => model.Age)
            @Html.ValidationMessageFor(model => model.Age)

            <br />
            @Html.LabelFor(model => model.Sex)
            @Html.EditorFor(model => model.Sex)
            @Html.ValidationMessageFor(model => model.EmpCode)

            <br />
            @Html.LabelFor(model => model.Email)
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)

            <br />
            <input type="submit" value="click me" />





        }


        <br />
        <br />

       

</body>

Poc_task/Views/Default/PostUsingBinding.cshtml
@model Poc_task.Models.Employee
@{
    ViewBag.Title = "PostUsingBinding";
}

<h2>DATA Added successfully</h2>

Poc_task/Views/Default/ViewRecords.cshtml
@model IEnumerable<Poc_task.Models.Employee>

@{
    ViewBag.Title = "ViewRecords";
}

<h2>ViewRecords</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmpCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sex)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmpCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sex)
        </td>
        
    </tr>
}

</table>